version: "3"

services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data:/data/db

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017

  node-web:
    image: node-web
    container_name: node_web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm run dev:watch
    env_file: ./app/.env
    ports:
      - 8081:80
    volumes:
      - /tmp/node-web/npm-cache:/root/.npm:z
      - ./app/src:/usr/app/src:z
    restart: always

  nginx:
    image: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - node-web:web
