version: "3"

services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data:/data/db

  cache:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017

  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://db:27017

  node-web:
    image: node-web
    container_name: node_web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm run dev:watch
    env_file: ./app/.env
    ports:
      - 8081:80
    volumes:
      - /tmp/node-web/npm-cache:/root/.npm:z
      - ./app/src:/usr/app/src:z
    restart: always
    links:
      - cache

  nginx:
    image: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - node-web:web

  kernel_gateway:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: hello-jup
    container_name: hello_jup
    ports:
      - "7777:7777"
      - "9999:9999"
    volumes:
      - "./jupyter/book/:/srv/notebooks:Z"
    user: root
    environment:
      CHOWN_HOME: "yes"
      HOWN_HOME_OPTS: "-R"
      KG_ALLOW_ORIGIN: "*"
      KG_LIST_KERNELS: "True"
      KG_AUTH_TOKEN: colonels
    # command: >
    #   jupyter kernelgateway
    #   --KernelGatewayApp.ip=0.0.0.0
    #   --KernelGatewayApp.log_level=DEBUG
# DOOOONE
